// Bake the fonts into the bundle as data URIs.
//
// @remotion/fonts wraps FontFace in a delayRender(), and on a long render that
// handle eventually failed to clear — the render died at frame 230 with
// "Loading font DM Sans ... was called but not cleared after 28000ms".
// A data URI has nothing to wait for: no fetch, no handle, no timeout.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const FONTS = join(HERE, '..', 'public', 'fonts');

const faces = [
  { family: 'DM Sans', file: 'dm-sans-latin-wght-normal.woff2', weight: '100 1000' },
  { family: 'JetBrains Mono', file: 'jetbrains-mono-latin-400-normal.woff2', weight: '400' },
  { family: 'JetBrains Mono', file: 'jetbrains-mono-latin-500-normal.woff2', weight: '500' },
  { family: 'JetBrains Mono', file: 'jetbrains-mono-latin-700-normal.woff2', weight: '700' },
];

const css = faces
  .map(({ family, file, weight }) => {
    const b64 = readFileSync(join(FONTS, file)).toString('base64');
    return `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};font-display:block;src:url(data:font/woff2;base64,${b64}) format('woff2');}`;
  })
  .join('\n');

const out = `// GENERATED by scripts/embed-fonts.mjs — do not edit.
// The app's own DM Sans and JetBrains Mono files, inlined so the renderer never
// has to wait on a font.

export const FONT_CSS = ${JSON.stringify(css)};
`;

writeFileSync(join(HERE, '..', 'src', 'brand', 'fonts.ts'), out);
console.log(
  `fonts.ts written — ${faces.length} faces, ${(css.length / 1024).toFixed(0)} KB of CSS`,
);
